defaults: &defaults

  # sites hosts
  # session expire seconds
  # admin role account
  URL_HOST: bongo.network
  URL_SCHEMA: http
  SESSION_EXPIRE: 60
  ADMIN: 'admin@peatio.dev,admin@example.com'
  TIMEZONE: 'Cairo'

  REDIS_URL: redis://127.0.0.1:6379

  # below settings only in production env
  # system notify mail settings
  # --------------------------------------------------------------
  SMTP_PORT: 587
  SMTP_DOMAIN: mailgun.org
  SMTP_ADDRESS: smtp.mailgun.org
  SMTP_USERNAME: postmaster@bongo.network
  SMTP_PASSWORD : 0bc226886db6bc784caf9df0dad4be7e-a5d1a068-f5f1de2b
  SMTP_AUTHENTICATION: plain # could be plain, login or cram_md5

  SUPPORT_MAIL: postmaster@bongo.network
  SYSTEM_MAIL_FROM: postmaster@bongo.network
  SYSTEM_MAIL_TO: postmaster@bongo.network
  OPERATE_MAIL_TO: postmaster@bongo.network

  # WebSocket Streaming API settings
  # --------------------------------------------------------------
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: 8080
  # Uncomment below to enable secure WebSocket (wss)
  #WEBSOCKET_SSL_KEY: 'your_server.key'
  #WEBSOCKET_SSL_CERT: 'your_server.crt'

  # pusher settings
  # --------------------------------------------------------------
  # peatio dependence Pusher (http://pusher.com) service
  # you can change your key for production environment.
  # we support development key and secret
  # uncomment below line only development or test
  #
  # PUSHER_APP: 65910
  # PUSHER_KEY: 50d404c35db92d736a57
  # PUSHER_SECRET: 75d6e6685209cc60cc4d

  PUSHER_APP: 568771
  PUSHER_KEY: ea0bd35e4abfd496fc2e
  PUSHER_SECRET: c60e2fd5821651e75188
  PUSHER_HOST: api.pusherapp.com
  PUSHER_PORT: 80
  PUSHER_WS_PORT: 80
  PUSHER_WSS_PORT: 443
  PUSHER_ENCRYPTED: true

  # twilio setting
  # --------------------------------------------------------------
  # https://github.com/twilio/twilio-ruby
  #
  TWILIO_NUMBER: +16012286546
  TWILIO_SID: AC7e1ae56c95f5b7ad46feedfd40f0d21f
  TWILIO_TOKEN: 07872ae0cb0e2b4c40bdd1121cb2b7c3


  # Third party auth

  # Weibo
  # --------------------------------------------------------------
  WEIBO_AUTH: off # on/off
  WEIBO_KEY: 3820920586
  WEIBO_SECRET: 2d6174dc698e86860c75d75b1e8a01c8

  # chat setting
  # --------------------------------------------------------------
  # Do you want chat feature in your exchange ?
  # send mail to community@peatio.com

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
